version: "3.8"

services:
  genai-app:
    build: .
    restart: "always"
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    networks:
      - app-net

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: "always"
    networks:
      - app-net

networks:
  app-net:

volumes:
  qdrant_storage:
    external: true